import { Button, Tag } from 'antd'
import { ArrowLeftOutlined, CalendarOutlined, CheckCircleOutlined, EnvironmentOutlined, MessageOutlined, ShareAltOutlined, TeamOutlined } from '@ant-design/icons'
import { Link, useParams } from 'react-router-dom'
import { getEvent } from '../data/events'
import NotFoundPage from './NotFoundPage'

export default function EventPage() {
  const event = getEvent(useParams().eventId ?? '')
  if (!event) return <NotFoundPage />
  return <div className="detail-page"><Link to="/events" className="back-link"><ArrowLeftOutlined /> Все события</Link><div className="detail-layout"><div className="detail-main"><div className="detail-cover"><img src={event.image} alt=""/><Tag className="detail-tag">{event.category}</Tag></div><div className="detail-heading"><div><div className="eyebrow">{event.dateLabel} · {event.time}</div><h1>{event.title}</h1></div><Button shape="circle" icon={<ShareAltOutlined />} aria-label="Поделиться" /></div><p className="detail-description">{event.description}</p><div className="detail-facts"><div><CalendarOutlined /><span><b>{event.dateLabel}</b><small>Начало в {event.time}</small></span></div><div><EnvironmentOutlined /><span><b>{event.venue}</b><small>{event.address}</small></span></div></div><div className="host-row"><span className={`host-avatar ${event.hostColor}`}>{event.hostInitials}</span><span>Организатор<br/><b>{event.host}</b></span><Tag bordered={false} color="green">Организатор</Tag></div></div><aside className="join-card"><div className="join-card-top"><span>КОМПАНИЯ СОБРАНА</span><div className="capacity"><strong>{event.going}</strong><span> из {event.capacity}<br/>участников</span></div><div className="capacity-track"><i style={{ width: `${event.going / event.capacity * 100}%` }}/></div><div className="join-avatars"><span>М</span><span>А</span><span>И</span><span>Л</span><span>+{Math.max(event.going - 4, 0)}</span></div><p>Люди, которым тоже интересно</p></div><div className="join-card-bottom"><div className="price-label">Участие <b>{event.price}</b></div><Button type="primary" size="large" block disabled>Запись появится позже</Button><small><CheckCircleOutlined /> Демонстрационный интерфейс</small><div className="join-links"><Link to={`/events/${event.id}/group`}><TeamOutlined /> Группа</Link><Link to={`/events/${event.id}/chat`}><MessageOutlined /> Чат</Link></div></div></aside></div></div>
}
